# Generated by Django 4.1.4 on 2023-02-18 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_add', models.PositiveIntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineShoppingApp.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('category_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineShoppingApp.categories')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineShoppingApp.customers')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineShoppingApp.customers')),
                ('order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineShoppingApp.shoppingorder')),
                ('payment_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineShoppingApp.payment')),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineShoppingApp.products')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineShoppingApp.products')),
            ],
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineShoppingApp.customers')),
            ],
        ),
    ]
